# 配置文档  https://github.com/estk/log4rs/blob/main/docs/Configuration.md
refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - requests
# TODO 下面这些可能是不必要的
loggers:
  app::backend::db:
    level: info
  app::requests:
    level: info
    appenders:
      - requests
    additive: false
