# 配置文档  https://github.com/estk/log4rs/blob/main/docs/Configuration.md
refresh_rate: 5 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] [{t}] {m}{n}"
  requests:
    kind: file
    path: "log/requests.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} [{l}] [{t}] {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - requests
